# Generated by Django 5.2.8 on 2026-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_playlist_like_playlistvideo_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hover_thumbnails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
