# Generated by Django 6.0.1 on 2026-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_hover_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
